# Generated by Django 4.2.7 on 2023-11-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='dia_jogo',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('jogos', models.ManyToManyField(to='jogos.jogo')),
            ],
        ),
    ]
