# Generated by Django 4.2.7 on 2023-11-21 13:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0002_alter_jogo_dia_jogo_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='jogo',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
